version: "3.9"

services:
  scanning_api_server:
    container_name: scanning_api
    image: alpine:latest
    build: .
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_URI=${POSTGRES_URI}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    restart: always
    entrypoint: "python3 scan_interface.py docker-local"